export default {
    SELECT_NUMBER: 'SELECT_NUMBER',
    ADVANCE_ROUND: 'ADVANCE_ROUND',
    ADVANCE_FRAME: 'ADVANCE_FRAME',
    ADD_SCORE: 'ADD_SCORE',
    END_GAME: 'END_GAME',
    RESTART: 'RESTART',
};
